In [73]:
import torch
import math
from torch import bmm

In [74]:
def step_by_step_batch_attention(Q, K, V):
    d_k = Q.size(-1)
    scores = bmm(Q, K.mT) / math.sqrt(d_k)
    print(f"scores = \n{scores}")
    score_probabilities = torch.softmax(scores, dim=-1)
    print(f"softmax(scores) = \n{score_probabilities}")
    assert torch.all((torch.sum(score_probabilities, dim=-1) - 1.0).abs() < 1e-6), "Softmax rows do not sum to 1"
    return bmm(score_probabilities, V)

In [75]:
# Sample values are small so that it's easier to check correctness of the calculations
n = 4 # words count
d = 2 # size of embedding
d_k = 3
batch_size = 2

X = torch.rand(n, d)
W_q = torch.rand(batch_size, d, d_k)
W_k = torch.rand(batch_size, d, d_k)
W_v = torch.rand(batch_size, d, d_k)

In [76]:
print(f"X = \n{X}")
print(f"W_q = \n{W_q}")
print(f"W_k = \n{W_k}")
print(f"W_v = \n{W_v}")

X = 
tensor([[0.4200, 0.6397],
        [0.0959, 0.6522],
        [0.2166, 0.6217],
        [0.0043, 0.1585]])
W_q = 
tensor([[[0.2429, 0.6981, 0.8631],
         [0.9737, 0.6650, 0.1249]],

        [[0.6034, 0.5414, 0.1640],
         [0.1006, 0.0570, 0.2317]]])
W_k = 
tensor([[[0.0011, 0.2411, 0.0838],
         [0.7602, 0.5133, 0.8025]],

        [[0.2455, 0.2113, 0.2452],
         [0.3567, 0.1613, 0.3139]]])
W_v = 
tensor([[[0.9755, 0.5472, 0.6808],
         [0.6955, 0.6186, 0.3801]],

        [[0.0022, 0.1157, 0.9115],
         [0.0389, 0.0145, 0.4569]]])


In [77]:
X_batch = X.unsqueeze(0).expand(batch_size, -1, -1)
Q = torch.bmm(X_batch, W_q)
K = torch.bmm(X_batch, W_k)
V = torch.bmm(X_batch, W_v)

print(f"Q = \n{Q}")
print(f"K = \n{K}")
print(f"V = \n{V}")

Q = 
tensor([[[0.7249, 0.7186, 0.4424],
         [0.6584, 0.5007, 0.1642],
         [0.6580, 0.5646, 0.2646],
         [0.1554, 0.1084, 0.0235]],

        [[0.3178, 0.2638, 0.2171],
         [0.1235, 0.0891, 0.1668],
         [0.1932, 0.1527, 0.1795],
         [0.0186, 0.0114, 0.0374]]])
K = 
tensor([[[0.4867, 0.4296, 0.5486],
         [0.4959, 0.3579, 0.5315],
         [0.4729, 0.3713, 0.5171],
         [0.1205, 0.0824, 0.1276]],

        [[0.3313, 0.1919, 0.3038],
         [0.2562, 0.1254, 0.2283],
         [0.2749, 0.1460, 0.2483],
         [0.0576, 0.0265, 0.0508]]])
V = 
tensor([[[0.8547, 0.6256, 0.5291],
         [0.5472, 0.4560, 0.3132],
         [0.6437, 0.5031, 0.3837],
         [0.1145, 0.1004, 0.0632]],

        [[0.0258, 0.0579, 0.6752],
         [0.0256, 0.0206, 0.3854],
         [0.0246, 0.0341, 0.4815],
         [0.0062, 0.0028, 0.0764]]])


In [78]:
attention_results = step_by_step_batch_attention(Q, K, V)

scores = 
tensor([[[0.5221, 0.4918, 0.4841, 0.1172],
         [0.3612, 0.3423, 0.3361, 0.0817],
         [0.4088, 0.3862, 0.3797, 0.0921],
         [0.0780, 0.0741, 0.0727, 0.0177]],

        [[0.1281, 0.0947, 0.1038, 0.0210],
         [0.0628, 0.0467, 0.0510, 0.0104],
         [0.0854, 0.0633, 0.0693, 0.0140],
         [0.0114, 0.0085, 0.0093, 0.0019]]])
softmax(scores) = 
tensor([[[0.2778, 0.2695, 0.2674, 0.1853],
         [0.2693, 0.2643, 0.2627, 0.2037],
         [0.2719, 0.2659, 0.2641, 0.1981],
         [0.2543, 0.2533, 0.2530, 0.2394]],

        [[0.2603, 0.2518, 0.2541, 0.2339],
         [0.2550, 0.2510, 0.2520, 0.2420],
         [0.2568, 0.2512, 0.2527, 0.2392],
         [0.2509, 0.2502, 0.2504, 0.2485]]])


In [79]:
print(f"attention = \n{attention_results}")

attention = 
tensor([[[0.5782, 0.4498, 0.3457],
         [0.5672, 0.4416, 0.3389],
         [0.5706, 0.4441, 0.3410],
         [0.5462, 0.4259, 0.3261]],

        [[0.0209, 0.0296, 0.4130],
         [0.0207, 0.0292, 0.4087],
         [0.0207, 0.0293, 0.4102],
         [0.0206, 0.0289, 0.4054]]])
